import random
import time

def generate_code(code_length):
    gentype = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    separator = '-'
    return separator.join(''.join(random.choice(gentype) for _ in range(code_length)) for _ in range(4)) + '\n'

def generate_codes(service, number, file):
    code_length = 16
    with open(file, 'a') as out:
        for _ in range(number):
            code = generate_code(code_length)
            out.write(code)

print("Hello To Multiple Gift Card Generator")
print("This Script Is Just for educational purpose; use it at your own risk")

while True:
    try:
        total = int(input("How Many Would You Like To Generate? "))
        break
    except ValueError:
        print("Please enter a valid number.")

services = [
    "Amazon", "Roblox", "Webkinz", "Fortnite", "IMVU", "Ebay", 
    "Netflix", "iTunes", "Paypal", "Visa", "PokemonTGC", "Playstation", 
    "Steam", "Xbox", "PlayStore", "Minecraft"
]

print("Which Would You Like To Generate?")
for idx, service in enumerate(services, 1):
    print(f"{idx}. {service}")

while True:
    try:
        selected_service = int(input("Enter the number of the service: ").strip())
        if 1 <= selected_service <= len(services):
            break
        else:
            print("Please enter a valid service number.")
    except ValueError:
        print("Please enter a valid number.")

file_name = f"{total} Generated By Multiple Gift Card Generator.txt"

print(f"Selected service: {services[selected_service - 1]}")

if selected_service - 1 in range(len(services)):
    generate_codes(selected_service - 1, total, file_name)
    print(f"Codes for {services[selected_service - 1]} generated successfully in {file_name}!")
else:
    print("Invalid service selection!")

print("Thanks For Using My Script")
time.sleep(5)
