import random
import time

def generate_code(length):
    gentype = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    separator = '-'
    return separator.join(random.choice(gentype) for _ in range(length)) + '\n'

print("Hello To Multiple Gift Card Generator")
print("This Script Is Just for educational purpose; use it at your own risk")

total = input("How Many Would You Like To Generate? ")
number = int(total)
file = total + " Generated By Multiple Gift Card Generator.txt"
file2 = 'GiftCardsCodes.txt'

services = {
    1: "Amazon", 2: "Roblox", 3: "Webkinz", 4: "Fortnite", 5: "IMVU", 6: "Ebay",
    7: "Netflix", 8: "iTunes", 9: "Paypal", 10: "Visa", 11: "PokemonTGC", 12: "Playstation",
    13: "Steam", 14: "Xbox", 15: "PlayStore", 16: "Minecraft"
}

print("Which Would You Like To Generate?")
for num, service in services.items():
    print(f"{num}. {service}")

selected_service = int(input("Enter the number of the service: ").strip())

if selected_service in services:
    mode = services[selected_service]
    with open(file, 'a') as out:
        for _ in range(number):
            if mode == "Visa":
                types = input("Card Or Prepaid Code? ")
                if types == "Prepaid Code":
                    code = generate_code(16)
                    out.write(code)
                    with open(file2, 'a') as out2:
                        out2.write(generate_code(6))
                elif types == "Card":
                    code = generate_code(24)
                    out.write(code)
            else:
                code = generate_code(16)
                out.write(code)

    print(f"Codes for {mode} generated successfully in {file}!")
else:
    print("Invalid service selection!")

print("Thanks For Using My Script")
time.sleep(5)
